version: '3.5'

services:
  payment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'payment'
    restart: always
    ports:
      - 3002:3002
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npx prisma generate && npm start"

networks:
  default:
    name: local
